root: true
env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  object-curly-spacing:
    - warn
    - always
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - warn
  no-console:
    - warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 2
  sort-imports:
    - warn
    - allowSeparatedGroups: true
      ignoreDeclarationSort: true
  import/order:
    - warn
    - alphabetize:
        order: asc
      newlines-between: always
      groups:
        [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type",
        ]
      pathGroups:
        - pattern: "react"
          group: builtin
        - pattern: "@src/*"
          group: parent
        - pattern: "./**"
          group: sibling